development:
        adapter: mysql2
        database: blacklight_dev
        username: blyul
        password: 2013%bL1!
        host: localhost
        port: 3306
test:
        adapter: mysql2
        database: blacklight_test
        username: blyul
        password: 2013%bL1!
        host: localhost
        port: 3306
production:
        adapter: mysql2
        database: blacklight
        username: blyul
        password: 2013%bL1!
        host: localhost
        port: 3306