# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora. 
development:
  url: http://libserver7.yale.edu:8083/solr/collection1
test: &TEST
  url: http://libserver7.yale.edu:8083/solr/collection1
cucumber:
  <<: *TEST
production:
  url: http://diego.library.yale.edu:8083/solr/collection1
